apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack
  namespace: openshift-logging
spec:
  size: 1x.demo
  storage:
    schemas:
    - version: v12
      effectiveDate: "2022-06-01"
    secret:
      name: s3-lokistack
      type: s3
  storageClassName: gp3
  tenants:
    mode: openshift-logging